name: maps_clone
description: A Google Maps clone.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auth_api:
    path: packages/auth_api
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  build_runner: ^2.1.7
  built_collection: ^5.1.1
  built_value: ^8.1.4
  cloud_firestore: ^4.3.0
  common_api:
    path: packages/common_api
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  equatable: ^2.0.3
  firebase_auth_api:
    path: packages/firebase_auth_api
  firebase_core_api:
    path: packages/firebase_core_api
  firebase_profile_api:
    path: packages/firebase_profile_api
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_polyline_points: ^1.0.0
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.1.5
  get: ^4.6.1
  google_maps_flutter: ^2.1.8
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_sign_in: ^5.3.3
  intl: ^0.17.0
  latlong2: ^0.8.1
  location: ^4.4.0
  logging: ^1.0.2
  profile_api:
    path: packages/profile_api
  profile_repository:
    path: packages/profile_repository
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/map_styles/
    - .env
