name: common_api
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.7
  built_value_generator: ^8.1.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter