name: firebase_profile_api
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.3.0
  flutter:
    sdk: flutter
  profile_api:
    path: '../profile_api'

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
